version: "3.8"
services:
  app:
    image: 912394945783.dkr.ecr.ap-northeast-2.amazonaws.com/vinny-backend:latest
    container_name: vinny-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
