version: "3.7"

networks:
  wisefee-network-dev-deploy:
    driver: bridge

services:
  wisefee-app:
    image: sjh9708/devserver-wisefee-app5:latest
    restart: always
    depends_on:
      - wisefee-redis
    ports:
      - "8082:8080"
    container_name: wisefee-app-dev-deploy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://jvinny.cnkkw26g66qk.ap-northeast-2.rds.amazonaws.com:3306/wisefee-database?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_REDIS_HOST: wisefee-redis-dev-deploy
      SPRING_REDIS_PORT: 6379
    volumes:
      - ./volumes/storage/upload:/app/wisefee/storage/upload
      - ./volumes/log:/app/wisefee/log
    networks:
      - wisefee-network-dev-deploy

  wisefee-redis:
    image: redis:6.2.6-alpine
    ports:
      - "6391:6379"
    container_name: wisefee-redis-dev-deploy
    restart: always
    networks:
      - wisefee-network-dev-deploy
