version: "3.8"
services:
  app:
    image: 912394945783.dkr.ecr.ap-northeast-2.amazonaws.com/vinny-project:latest
    container_name: vinny-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/redis-data:/data
      - /home/ubuntu/redis.conf:/redis-stack/redis.conf
    command: [ "redis-server", "/redis-stack/redis.conf" ]
    restart: always
