spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  logging:
    level:
      org.springframework.boot.autoconfigure.jdbc: DEBUG


  # OAuth2 설정 구조
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: kakao${KAKAO_NATIVE_APP_KEY}://oauth
            scope:
              - profile_nickname
              - profile_image
              - account_email
        #          apple:
        #            client-id: ${APPLE_CLIENT_ID}
        #            client-authentication-method: client_secret_post
        #            authorization-grant-type: authorization_code
        #            redirect-uri: https://your-domain.com/api/auth/login/apple/callback # 임시 도메인
        #            scope:
        #              - name
        #              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#          apple:
#            token-uri: https://appleid.apple.com/auth/token
#            jwk-set-uri: https://appleid.apple.com/auth/keys

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-milliseconds: 1800000 # 30분
  #  access-token-expiration-milliseconds: 5000 # 5초 -> refreshToken 테스트용
  refresh-token-expiration-milliseconds: 604800000 # 7일 (이건 그대로 둡니다)

# Apple 로그인 전용 설정값
#apple:
#  team-id: ${APPLE_TEAM_ID}
#  key-id: ${APPLE_KEY_ID}
#  private-key-path: ${APPLE_PRIVATE_KEY_PATH}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: "vinny-bucket-s3"
    region:
      static: "ap-northeast-2"
    stack:
      auto: false