#spring:
#  profiles:
#    active: local

spring:
  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL # 인메모리 모드 및 MySQL 호환 모드
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  # H2 웹 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 스키마 자동 변경
    properties:
      hibernate:
        show_sql: true # 실행되는 SQL 쿼리 로그로 출력
        format_sql: true # SQL 쿼리 예쁘게 포매팅
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

jwt:
  secret: "your-super-secret-key-that-is-long-enough-to-be-secure-your-super-secret-key-that-is-long-enough-to-be-secure"
  access-token-expiration-milliseconds: 1800000 # 30분
#  access-token-expiration-milliseconds: 5000 # 5초 -> refreshToken 테스트용
  refresh-token-expiration-milliseconds: 604800000 # 7일 (이건 그대로 둡니다)