spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/vinny
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  logging:
    level:
      org.springframework.boot.autoconfigure.jdbc: DEBUG


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-milliseconds: 1800000 # 30분
  #  access-token-expiration-milliseconds: 5000 # 5초 -> refreshToken 테스트용
  refresh-token-expiration-milliseconds: 604800000 # 7일 (이건 그대로 둡니다)

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: "vinny-bucket-s3"
    region:
      static: "ap-northeast-2"
    stack:
      auto: false