spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/vinny
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: "your-super-secret-key-that-is-long-enough-to-be-secure-your-super-secret-key-that-is-long-enough-to-be-secure"
  access-token-expiration-milliseconds: 1800000 # 30분
  #  access-token-expiration-milliseconds: 5000 # 5초 -> refreshToken 테스트용
  refresh-token-expiration-milliseconds: 604800000 # 7일 (이건 그대로 둡니다)