spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/vinny
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-milliseconds: 1800000 # 30분
  refresh-token-expiration-milliseconds: 604800000 # 7일 (이건 그대로 둡니다)

cloud:
  aws:
    credentials:
      access-key: ${access_key}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: "vinny-bucket-s3"
    region:
      static: "ap-northeast-2"
    stack:
      auto: false
